version: 2.1

py35: &py35
  docker:
    - image: circleci/python:3.5.7-stretch
  working_directory: ~/qc-utils

py36: &py36
  docker:
    - image: circleci/python:3.6.7-stretch
  working_directory: ~/qc-utils

py37: &py37
  docker: 
    - image: circleci/python:3.7.3-stretch
  working_directory: ~/qc-utils

py38: &py38
  docker: 
    - image: circleci/python:3.8.0b1-stretch
  working_directory: ~/qc-utils


jobs:
  py35_unit:
    <<: *py35
    steps:
      - checkout
      - run:
          name: py35
          command: |
            sudo pip install tox
            tox -e py35
workflows:
  build_workflow:
    jobs:
      - py35_unit
