version: 2.1

# default envs
py36: &py36
  docker:
    - image: circleci/python:3.6.7-stretch
  working_directory: ~/qc-utils

py37: &py37
  docker:
    - image: circleci/python:3.7.3-stretch
  working_directory: ~/qc-utils

py38: &py38
  docker:
    - image: circleci/python:3.8.0b1-stretch
  working_directory: ~/qc-utils

defaults: &defaults
  docker:
    - image: circleci/buildpack-deps:xenial-scm
  working_directory: ~/qc-utils

master_only: &master_only
  filters:
    branches:
      only:
        - master

commands:

  run_tox:
    description: "A very simple command for demonstration purposes"
    parameters:
      toxenv:
        type: string
    steps:
      - run: sudo pip install tox
      - run: tox -e << parameters.toxenv >>


jobs:

  lint:
    <<: *py37
    steps:
      - checkout
      - run_tox:
          toxenv: "lint"

  py36_unit:
    <<: *py36
    steps:
      - checkout
      - run_tox:
          toxenv: "py36"

  py37_unit:
    <<: *py37
    steps:
      - checkout
      - run_tox:
          toxenv: "py37"

  py38_unit:
    <<: *py38
    steps:
      - checkout
      - run_tox:
          toxenv: "py38"

  docs:
    <<: *py37
    steps:
      - checkout
      - run_tox:
          toxenv: "docs"

  pypi-description:
    <<: *py37
    steps:
      - checkout
      - run_tox:
          toxenv: "pypi-description"

  coverage-report:
    <<: *py37
    steps:
      - checkout
      - run_tox:
          toxenv: "coverage-report"

  release_to_pypi:
    <<: *py37
    steps:
      - checkout
      - run: sudo pip install --upgrade setuptools wheel twine
      - run: ./release_to_pypi.sh https://upload.pypi.org/legacy/

workflows:
  build_workflow:
    jobs:
      - lint
      - py36_unit
      - py37_unit
      - py38_unit
      - docs
      - pypi-description
      - coverage-report
      - release_to_pypi:
          <<: *master_only
          requires:
            - lint
            - py36_unit
            - py37_unit
            - py38_unit
            - docs
            - coverage-report
