version: 2.1

# default envs
py35: &py35
  docker:
    - image: circleci/python:3.5.7-stretch
  working_directory: ~/qc-utils

py36: &py36
  docker:
    - image: circleci/python:3.6.7-stretch
  working_directory: ~/qc-utils

py37: &py37
  docker:
    - image: circleci/python:3.7.3-stretch
  working_directory: ~/qc-utils

py38: &py38
  docker:
    - image: circleci/python:3.8.0b1-stretch
  working_directory: ~/qc-utils


commands:

  run_tox:
    description: "A very simple command for demonstration purposes"
    parameters:
      to:
        type: string
    steps:
      - run: sudo pip install tox
      - run: tox -e << parameters.to >>


jobs:
  py35_unit:
    <<: *py35
    steps:
      - checkout
      - run_tox:
          to: "py35"

  py36_unit:
    <<: *py36
    steps:
      - checkout
      - run: sudo pip install --upgrade setuptools
      - run_tox:
          to: "py36"

  py37_unit:
    <<: *py37
    steps:
      - checkout
      - run_tox:
          to: "py37"

  py38_unit:
    <<: *py38
    steps:
      - checkout
      - run_tox:
          to: "py38"


workflows:
  build_workflow:
    jobs:
      - py35_unit
      - py36_unit
      - py37_unit
      - py38_unit
